import { AGEDocument } from '../interfaces/age.interface';

export const renderAgeXML = (doc: AGEDocument): string => `
<?xml version="1.0" encoding="UTF-8"?>
<ns3:FatturaElettronica versione="FPR12"
  xmlns:ns2="http://www.w3.org/2000/09/xmldsig#"
  xmlns:ns3="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2">
  <FatturaElettronicaHeader>
    <DatiTrasmissione>
      <ProgressivoInvio>${doc.FatturaElettronicaHeader.DatiTrasmissione.ProgressivoInvio}</ProgressivoInvio>
      <FormatoTrasmissione>${doc.FatturaElettronicaHeader.DatiTrasmissione.FormatoTrasmissione}</FormatoTrasmissione>
      <CodiceDestinatario>${doc.FatturaElettronicaHeader.DatiTrasmissione.CodiceDestinatario}</CodiceDestinatario>
      <IdTrasmittente>
        <IdPaese>${doc.FatturaElettronicaHeader.DatiTrasmissione.IdTrasmittente.IdPaese}</IdPaese>
        <IdCodice>${doc.FatturaElettronicaHeader.DatiTrasmissione.IdTrasmittente.IdCodice}</IdCodice>
      </IdTrasmittente>
      <ContattiTrasmittente>
        <Telefono>${doc.FatturaElettronicaHeader.DatiTrasmissione.ContattiTrasmittente.Telefono}</Telefono>
      </ContattiTrasmittente>
    </DatiTrasmissione>
    <CedentePrestatore>
      <DatiAnagrafici>
        <IdFiscaleIVA>
          <IdPaese>${doc.FatturaElettronicaHeader.CedentePrestatore.DatiAnagrafici.IdFiscaleIVA.IdPaese}</IdPaese>
          <IdCodice>${doc.FatturaElettronicaHeader.CedentePrestatore.DatiAnagrafici.IdFiscaleIVA.IdCodice}</IdCodice>
        </IdFiscaleIVA>
        <CodiceFiscale>${doc.FatturaElettronicaHeader.CedentePrestatore.DatiAnagrafici.CodiceFiscale}</CodiceFiscale>
        <Anagrafica>
          <Denominazione>${doc.FatturaElettronicaHeader.CedentePrestatore.DatiAnagrafici.Anagrafica.Denominazione}</Denominazione>
        </Anagrafica>
        <RegimeFiscale>${doc.FatturaElettronicaHeader.CedentePrestatore.DatiAnagrafici.RegimeFiscale}</RegimeFiscale>
      </DatiAnagrafici>
      <Sede>
        <Indirizzo>${doc.FatturaElettronicaHeader.CedentePrestatore.Sede.Indirizzo}</Indirizzo>
        <CAP>${doc.FatturaElettronicaHeader.CedentePrestatore.Sede.CAP}</CAP>
        <Comune>${doc.FatturaElettronicaHeader.CedentePrestatore.Sede.Comune}</Comune>
        <Provincia>${doc.FatturaElettronicaHeader.CedentePrestatore.Sede.Provincia}</Provincia>
        <Nazione>${doc.FatturaElettronicaHeader.CedentePrestatore.Sede.Nazione}</Nazione>
      </Sede>
      <IscrizioneREA>
        <Ufficio>${doc.FatturaElettronicaHeader.CedentePrestatore.IscrizioneREA.Ufficio}</Ufficio>
        <NumeroREA>${doc.FatturaElettronicaHeader.CedentePrestatore.IscrizioneREA.NumeroREA}</NumeroREA>
        <StatoLiquidazione>${doc.FatturaElettronicaHeader.CedentePrestatore.IscrizioneREA.StatoLiquidazione}</StatoLiquidazione>
      </IscrizioneREA>
    </CedentePrestatore>
    <CessionarioCommittente>
      <DatiAnagrafici>
        <IdFiscaleIVA>
          <IdPaese>${doc.FatturaElettronicaHeader.CessionarioCommittente.DatiAnagrafici.IdFiscaleIVA.IdPaese}</IdPaese>
          <IdCodice>${doc.FatturaElettronicaHeader.CessionarioCommittente.DatiAnagrafici.IdFiscaleIVA.IdCodice}</IdCodice>
        </IdFiscaleIVA>
        <CodiceFiscale>${doc.FatturaElettronicaHeader.CessionarioCommittente.DatiAnagrafici.CodiceFiscale}</CodiceFiscale>
        <Anagrafica>
          <Denominazione>${doc.FatturaElettronicaHeader.CessionarioCommittente.DatiAnagrafici.Anagrafica.Denominazione}</Denominazione>
        </Anagrafica>
        <RegimeFiscale>${doc.FatturaElettronicaHeader.CessionarioCommittente.DatiAnagrafici.RegimeFiscale}</RegimeFiscale>
      </DatiAnagrafici>
      <Sede>
        <Indirizzo>${doc.FatturaElettronicaHeader.CessionarioCommittente.Sede.Indirizzo}</Indirizzo>
        <CAP>${doc.FatturaElettronicaHeader.CessionarioCommittente.Sede.CAP}</CAP>
        <Comune>${doc.FatturaElettronicaHeader.CessionarioCommittente.Sede.Comune}</Comune>
        <Provincia>${doc.FatturaElettronicaHeader.CessionarioCommittente.Sede.Provincia}</Provincia>
        <Nazione>${doc.FatturaElettronicaHeader.CessionarioCommittente.Sede.Nazione}</Nazione>
      </Sede>
    </CessionarioCommittente>
  </FatturaElettronicaHeader>
  <FatturaElettronicaBody>
    <DatiGenerali>
      <DatiGeneraliDocumento>
        <TipoDocumento>${doc.FatturaElettronicaBody.DatiGenerali.DatiGeneraliDocumento.TipoDocumento}</TipoDocumento>
        <Divisa>${doc.FatturaElettronicaBody.DatiGenerali.DatiGeneraliDocumento.Divisa}</Divisa>
        <Data>${doc.FatturaElettronicaBody.DatiGenerali.DatiGeneraliDocumento.Data}</Data>
        <Numero>${doc.FatturaElettronicaBody.DatiGenerali.DatiGeneraliDocumento.Numero}</Numero>
        <DatiBollo>
          <BolloVirtuale>${doc.FatturaElettronicaBody.DatiGenerali.DatiGeneraliDocumento.DatiBollo.BolloVirtuale}</BolloVirtuale>
          <ImportoBollo>${doc.FatturaElettronicaBody.DatiGenerali.DatiGeneraliDocumento.DatiBollo.ImportoBollo}</ImportoBollo>
        </DatiBollo>
        <ImportoTotaleDocumento>${doc.FatturaElettronicaBody.DatiGenerali.DatiGeneraliDocumento.ImportoTotaleDocumento}</ImportoTotaleDocumento>
        <Causale>${doc.FatturaElettronicaBody.DatiGenerali.DatiGeneraliDocumento.Causale}</Causale>
      </DatiGeneraliDocumento>
    </DatiGenerali>
    <DatiBeniServizi>
      <DettaglioLinee>
        <NumeroLinea>${doc.FatturaElettronicaBody.DatiBeniServizi.DettaglioLinee.NumeroLinea}</NumeroLinea>
        <Descrizione>${doc.FatturaElettronicaBody.DatiBeniServizi.DettaglioLinee.Descrizione}</Descrizione>
        <Quantita>${doc.FatturaElettronicaBody.DatiBeniServizi.DettaglioLinee.Quantita}</Quantita>
        <PrezzoUnitario>${doc.FatturaElettronicaBody.DatiBeniServizi.DettaglioLinee.PrezzoUnitario}</PrezzoUnitario>
        <PrezzoTotale>${doc.FatturaElettronicaBody.DatiBeniServizi.DettaglioLinee.PrezzoTotale}</PrezzoTotale>
        <AliquotaIVA>${doc.FatturaElettronicaBody.DatiBeniServizi.DettaglioLinee.AliquotaIva}</AliquotaIVA>
        <Natura>${doc.FatturaElettronicaBody.DatiBeniServizi.DettaglioLinee.Natura}</Natura>
      </DettaglioLinee>
      <DatiRiepilogo>
        <AliquotaIVA>${doc.FatturaElettronicaBody.DatiBeniServizi.DatiRiepilogo.AliquotaIva}</AliquotaIVA>
        <Natura>${doc.FatturaElettronicaBody.DatiBeniServizi.DatiRiepilogo.Natura}</Natura>
        <Arrotondamento>${doc.FatturaElettronicaBody.DatiBeniServizi.DatiRiepilogo.Arrotondamento}</Arrotondamento>
        <ImponibileImporto>${doc.FatturaElettronicaBody.DatiBeniServizi.DatiRiepilogo.ImponibileImporto}</ImponibileImporto>
        <Imposta>${doc.FatturaElettronicaBody.DatiBeniServizi.DatiRiepilogo.Imposta}</Imposta>
      </DatiRiepilogo>
    </DatiBeniServizi>
    <DatiPagamento>
      <CondizioniPagamento>${doc.FatturaElettronicaBody.DatiPagamento.CondizioniPagamento}</CondizioniPagamento>
      <DettaglioPagamento>
        <Beneficiario>${doc.FatturaElettronicaBody.DatiPagamento.DettaglioPagamento.Beneficiario}</Beneficiario>
        <ModalitaPagamento>${doc.FatturaElettronicaBody.DatiPagamento.DettaglioPagamento.Beneficiario}</ModalitaPagamento>
        <DataRiferimentoTerminiPagamento>${doc.FatturaElettronicaBody.DatiPagamento.DettaglioPagamento.DataRiferimentoTerminiPagamento}</DataRiferimentoTerminiPagamento>
        <ImportoPagamento>${doc.FatturaElettronicaBody.DatiPagamento.DettaglioPagamento.ImportoPagamento}</ImportoPagamento>
        <IstitutoFinanziario>${doc.FatturaElettronicaBody.DatiPagamento.DettaglioPagamento.IstitutoFinanziario}</IstitutoFinanziario>
        <IBAN>${doc.FatturaElettronicaBody.DatiPagamento.DettaglioPagamento.IBAN}</IBAN>
        <ABI>${doc.FatturaElettronicaBody.DatiPagamento.DettaglioPagamento.ABI}</ABI>
        <CAB>${doc.FatturaElettronicaBody.DatiPagamento.DettaglioPagamento.CAB}</CAB>
      </DettaglioPagamento>
    </DatiPagamento>
  </FatturaElettronicaBody>
</ns3:FatturaElettronica>
`;
